name: Build Python Executables

on:
  push:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller --onefile mdconv.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: gitbook_pdf_export-${{ matrix.os }}
          path: dist/gitbook_pdf_export*

  build-freebsd:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build on FreeBSD
        uses: vmactions/freebsd-vm@v1
        with:
          release: '14.2'
          usesh: true
          prepare: |
            pkg update -f
            pkg install -y python3 py38-pip git
            python3 -m ensurepip
            python3 -m pip install --upgrade pip
            python3 -m pip install -r requirements.txt
            python3 -m pip install pyinstaller
          run: |
            pyinstaller --onefile mdconv.py
            mkdir -p /artifacts
            cp dist/gitbook_pdf_export /artifacts/
      - name: Upload FreeBSD artifact
        uses: actions/upload-artifact@v4
        with:
          name: gitbook_pdf_export-freebsd
          path: artifacts/gitbook_pdf_export
